Handle `cacerts_sha256sum.txt` files if present (SOFTWARE-3004)

diff --git a/repo-update-cadist b/repo-update-cadist
--- a/repo-update-cadist
+++ b/repo-update-cadist
@@ -136,7 +136,7 @@ for TYPES in NEW IGTFNEW; do
 
 
     ## Download the "version" file from SVN - this has a name like
-    ## ca-certs-version-1.59NEW and is a txt file with the md5sum of the
+    ## ca-certs-version-1.59NEW and is a txt file with the checksum of the
     ## tarball in it. Then rename it to add the "-new" or "-igtf-new"
     ## suffix.
     VERSIONFILE_URL=${CADISTREPO}/${CADISTREPORELEASETYPE}/ca-certs-version-${VERSION_CA}${SUFFIX}
@@ -176,19 +176,32 @@ for TYPES in NEW IGTFNEW; do
     ## Extract INDEX.txt and CHANGES file; move them appropriately
     tar --no-same-owner -zxf "${CATARBALL}" -C "$CADIR"
     mv ${EXTRACT_FILES} "$CADIR"
-    # also get the cacerts_md5sum.txt file which has the md5sums of the
-    # individual certs inside the tarball and rename it to add the "-new"
-    # or "-igtf-new" suffix
-    mv certificates/cacerts_md5sum.txt ${TMPROOT}/cadist/cacerts_md5sum${FILEEXT}.txt
+    # also get the cacerts_md5sum.txt or cacerts_sha256sum.txt file which has
+    # the checksums of the individual certs inside the tarball and rename it to
+    # add the "-new" or "-igtf-new" suffix
+    foundsum=false
+    if [[ -f certificates/cacerts_sha256sum.txt ]]; then
+        mv certificates/cacerts_sha256sum.txt ${TMPROOT}/cadist/cacerts_sha256sum${FILEEXT}.txt
+        foundsum=true
+    fi
+    if [[ -f certificates/cacerts_md5sum.txt ]]; then
+        mv certificates/cacerts_md5sum.txt ${TMPROOT}/cadist/cacerts_md5sum${FILEEXT}.txt
+        foundsum=true
+    fi
+    if ! $foundsum; then
+        echo "checksum txt file not found for $TYPES"
+        exit 1
+    fi
     # clean up
     rm -rf "${CADIR}/certificates/"
 
-    # Update links in INDEX.html to point to the renamed locations of
-    # the ca-certs-version and cacerts_md5sum.txt files (e.g.
-    # "ca-certs-version-new" and "cacerts_md5sum-new.txt")
+    # Update links in INDEX.html to point to the renamed locations of the
+    # ca-certs-version, cacerts_md5sum.txt, and/or cacerts_sha256sum.txt files
+    # (e.g.  "ca-certs-version-new" and "cacerts_md5sum-new.txt")
     # (SOFTWARE-2746)
     sed -i -e "s|href='ca-certs-version'|href='ca-certs-version${FILEEXT}'|" \
            -e "s|href='cacerts_md5sum.txt'|href='cacerts_md5sum${FILEEXT}.txt'|" \
+           -e "s|href='cacerts_sha256sum.txt'|href='cacerts_sha256sum${FILEEXT}.txt'|" \
            ${TMPROOT}/cadist/${VERSION_CA}${SUFFIX}/INDEX.html
 
     ## Create relevant symlinks including current distro
