Add --testing option to download from osg-testing repo (SOFTWARE-3098)

diff --git a/repo-update-cadist b/repo-update-cadist
--- a/repo-update-cadist
+++ b/repo-update-cadist
@@ -15,6 +15,41 @@ RPMREPO=osg
 OSG_SECURITY_PUBKEY_URL=https://twiki.opensciencegrid.org/twiki/pub/Security/SecurityTeamMembers/osg-security-pubkey.asc
 OSG_SECURITY_PUBKEY=$(basename "$OSG_SECURITY_PUBKEY_URL")
 
+usage () {
+    echo "Usage: $(basename "$0") [--testing]" >&2
+    echo "  --testing    Download from the \"osg-testing\" repositories (instead of \"osg\")" >&2
+    echo "  -h|--help    This message" >&2
+}
+
+temp=$(getopt -o 'h' --long 'help,testing' -n "$(basename "$0")" -- "$@")
+if [[ $? != 0 ]]; then
+    echo "Usage error" >&2
+    usage
+    exit 2
+fi
+eval set -- "$temp"
+while true; do
+    case $1 in
+    -h|--help)
+        usage
+        exit 0
+    ;;
+    --testing)
+        RPMREPO=osg-testing
+        shift
+    ;;
+    --)
+        shift
+        break
+    ;;
+    *)
+        echo "Internal error parsing options" >&2
+        exit 1
+    ;;
+    esac
+done
+
+
 LOGREDIRECTFILENAME="/var/log/repo-update-cadist"
 
 # Redirect all stderr output to file
